name: Run tests and upload coverage

on:
  push:
    branches: 
      - '**'

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/feature/chtnnh/automating-lambda-tag-updation') && 'test' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare requirements.txt
      run: |
        sed 's/GITHUB_TOKEN_PLACEHOLDER/${{ secrets.ACCESS_TOKEN_GITHUB }}/g' requirements.txt > requirements_temp.txt
        mv requirements_temp.txt requirements.txt
    - name: Install dependencies
      id: install-dependencies
      run: |
        # Install universal virtualenv
        python -m pip install uv
        # Create a virtual environment
        uv venv
        source .venv/bin/activate
        # Use uv to install dependencies
        uv pip install -r requirements.txt
    - name: Run tests and generate coverage
      id: generate-test-coverage
      run: |
        # Python example
        source .venv/bin/activate
        uv pip install coverage pytest
        coverage run -m pytest tests/
        coverage xml -o coverage.xml
        cat coverage.xml
        
    - name: Upload coverage to CodeAnt AI
      uses: CodeAnt-AI/codeant-coverage-action@v0.0.5
      with:
          access_token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          coverage_file: coverage.xml
          
    
