name: CodeAnt CI Scan

on:
  push:
    branches: 
      - '**'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run CodeAnt Scan
        uses: CodeAnt-AI/codeant-ci-scan@v0.0.1
        with:
          access_token: ${{ secrets.ACCESS_TOKEN_GITHUB }}